spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
